import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import HeaderMobile from '@/components/HeaderMobile';
import Footer from '@/components/Footer';
import FooterMobile from '@/components/FooterMobile';


export const metadata: Metadata = {
  title: 'Hemart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <HeaderMobile/>
        {children}
        <FooterMobile/>
        <Footer />
      </body>
    </html>
  );
}
