export const paymentMethods = [
  {
    name: 'Bank Mandiri',
    instructions: [
      'Open the Mandiri Online app',
      'Log in with your username and password',
      'Select the "Transfer" menu',
      'Choose "To Mandiri Account"',
      'Enter the destination account number: 1234567890',
      'Enter the transfer amount',
      'Confirm and complete the transaction',
      'Screenshot your payment proof',
      'Upload the proof on your order details',
    ],
    icon: {
      src: '/icons/mandiri.webp',
      alt: 'Bank Mandiri logo',
      width: 100,
      height: 100,
    },
  },
  {
    name: 'Bank BCA',
    instructions: [
      'Open the BCA Mobile app',
      'Log in with your access code',
      'Select the "m-Transfer" menu',
      'Choose "Transfer" and "To BCA Account"',
      'Enter the destination account: 90123456',
      'Enter the transfer amount',
      'Confirm and complete the transaction',
      'Screenshot your payment proof',
      'Upload the proof on your order details',
    ],
    icon: {
      src: '/icons/bca.png',
      alt: 'Bank BCA logo',
      width: 100,
      height: 100,
    },
  },
  {
    name: 'Bank BRI',
    instructions: [
      'Open the BRImo app',
      'Log in with your username and password',
      'Select the "Transfer" menu',
      'Choose "To BRI Account"',
      'Enter the destination account number: 0987654321',
      'Enter the transfer amount',
      'Confirm and complete the transaction',
      'Screenshot your payment proof',
      'Upload the proof on your order details',
    ],
    icon: {
      src: '/icons/bri.png',
      alt: 'Bank BRI logo',
      width: 100,
      height: 100,
    },
  },
  {
    name: 'Bank BNI',
    instructions: [
      'Open the BNI Mobile Banking app',
      'Log in with your username and MPIN',
      'Select the "Transfer" menu',
      'Choose "To BNI Account"',
      'Enter the destination account number: 5678901234',
      'Enter the transfer amount',
      'Confirm and complete the transaction',
      'Screenshot your payment proof',
      'Upload the proof on your order details',
    ],
    icon: {
      src: '/icons/bni.png',
      alt: 'Bank BNI logo',
      width: 100,
      height: 100,
    },
  },
];
